language: go

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - tip

script:
  - GO111MODULE=on go test -v -cover -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
